#ifndef NAVIDROME_CONFIG_H
#define NAVIDROME_CONFIG_H

#define NAVIDROME_HOST "192.168.1.2"
#define NAVIDROME_PORT 4533U
#define NAVIDROME_USER "YOUR_SUBSONIC_USER"
#define NAVIDROME_PASSWORD "YOUR_SUBSONIC_PASSWORD"

#endif

